name: tgftools
channels:
  - defaults
dependencies:
  - python=3.11
  - numpy=1.25.2
  - pandas=2.0.3
  - matplotlib=3.7.1
  - pathlib=1.0.1
  - scipy=1.11.1
  - pytest=7.4.0
  - isort=5.9.3
  - black=23.3.0
  - openpyxl=3.0.10
  - gitpython=3.1.37
  - seaborn=0.12.2
  - dill=0.3.7
  - xlrd=2.0.1
  - reportlab=3.6.12
  - pip=23.3.1
  - jupyter
  - pip:
      - mkdocstrings
      - chardet==5.2.0
      - mkdocstrings-python==1.7.5
      - mkdocs-material==9.4.10
