import os
from typing import Dict

import pandas as pd
import pathlib

path_to_data_for_tests = (
    pathlib.Path(os.path.dirname(__file__)) / "code_and_data_for_tests"
)

def run_ic8_report(filename: pathlib.Path) -> Dict:
    """Returns the results generated by the running the Report class. (Also generates that Excel file in a temporary
    location.)"""

    # Warning to ensure this runs make sure in the parameters.toml you choose the full list of countries for portfolio
    # and modelled countries, otherwise this code will throw and error.
    # todo - see issue #58

    from scripts.ic8.analyses.main_results_for_investment_case import get_report

    r = get_report(
        load_data_from_raw_files=True,
        do_checks=False,
        run_analysis=True,
    )

    # Generate report (checking that it can be written to an Excel file)
    rtn_from_return = r.report(filename)

    # Return the results of the report
    return rtn_from_return


def test_ic8report(tmpdir):
    """
    This test runs the report for IC8 (including loading the model results from scratch and running the optimisation
     analysis) and checks that the results are the same as that obtained previously and which have been agreed to be
     the desired output from this code pipeline. In so doing, it also causes the report to be written to the Excel file
     - but these ancillary outputs are not scrutinized in this test.
    """

    def make_sorted_series(df: pd.DataFrame) -> pd.Series:
        return df.set_index(['Function', 'Key']).sort_index()['Value']

    filename = tmpdir / 'test_report_ic8.xlsx'
    run_results = run_ic8_report(filename)

    target_results = pd.read_csv(path_to_data_for_tests / 'IC8_Report_main_2025_02_24.csv')

    # Check for close agreement of the "main" results
    pd.testing.assert_series_equal(
        make_sorted_series(run_results["stats"]),
        make_sorted_series(target_results),
        rtol=0.001,   # Relative tolerance for comparison
    )

    # from tgftools.utils import open_file
    # open_file(filename)